trigger:
  - release/win

pool:
  vmImage: "vs2017-win2016"

steps:
  - bash: "./build_release.sh"
    workingDirectory: "megasource"
  - task: DownloadSecureFile@1
    inputs:
      secureFile: "ci-secret-file.txt"
  - bash: "./upload_release.sh"
    workingDirectory: "megasource"
    condition: ne(variables['Build.Reason'], 'PullRequest')
