jobs:
  build_beta_ios:
    macos:
      xcode: "11.2.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "mobile/Gemfile.lock" }}
      - run:
          name: bundle install
          command: |
              pushd mobile
              bundle check || bundle install --path vendor/bundle
              popd
      - save_cache:
          key: 1-gems-{{ checksum "mobile/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build and upload
          command: cd mobile && ./tools/upload-beta-build.sh
      - store_artifacts:
          path: output
workflows:
  version: 2
  build:
    jobs:
      - build_beta_ios:
          filters:
            branches:
              only:
                - beta/ios