version: 2
jobs:
  build:
    branches:
      only:
        - release/macos
        - ben/new-love-mpg123

    macos:
      xcode: "11.2.1"

    steps:
      - checkout

      - run:
          name: Build and Upload
          command: cd macosx && ./release.sh --no-upload

      - store_artifacts:
          path: /tmp/castle-notarize-artifacts
